services:
  - type: web
    name: english-learning-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: english_learning_ms5b
          property: connectionString
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
      - key: CORS_ORIGIN
        value: https://your-frontend-url.netlify.app
      - key: NODE_ENV
        value: production

databases:
  - name: english_learning_ms5b
    plan: free
